### ISSUE TITLE
Add Site Active/Inactive State

### ISSUE THREAD

**Issue by bamboochow** [whynotearth/foodouken.com#336]
# Design File
For design reference, please see files in [Figma](https://www.figma.com/file/Q671pbdFk3omco20xmxk5o/foodouken.com?node-id=2887%3A1)

Can be found in Foodouken Tenant CMS under setting page

# Active / Inactive Toggle 
We are giving users the ability to make their site active or inactive by using a toggle that we are adding to https://staging.foodouken.com/settings/account for their tenant card. 

Inactive / draft mode: 
- able to add/edit menu items and categories 
- Store site on home page/store page shown as "coming soon"
- Not able to click into store page from foodouken.com
- Visitors coming from direct store link (e.g. https://foodouken.com/shop/angkor-tacos-1 ) will be redirect to foodouken.com

Active: 
- able to add/edit menu items and categories 
- Store site is visible
- customers are able to send in delivery orders 

USE THIS CODE: 

Toggle: https://github.com/whynotearth/foodouken.com/blob/staging/src/components/inputs/BaseToggleSwitch.vue

![image](https://user-images.githubusercontent.com/14948326/87395352-6b7bb300-c5db-11ea-9d12-b32537888ceb.png)

**Content**
Title: Site Activation
Subtitle: Current Status: {Draft mode OR Active}

**Color**
Title: On Surface, High (#FFFFFF, 84%) 
Subtitle: On Surface, Medium (#FFFFFF, 54%) 
Inactive Toggle Knob: Primary (#437784)
Inactive Toggle Track: Divider (#FFFFFF, 12%) 
Active Toggle Knob: Secondary (#0E9EC2)
Active Toggle Track: Secondary, Medium (#0E9EC2, 54%) 

**Text Style** 
Title: 
```
/* Mobile Body */

font-family: Open Sans;
font-style: normal;
font-weight: normal;
font-size: 16px;
line-height: 22px;
```

Subtitle: 
```
/* Mobile Caption */

font-family: Open Sans;
font-style: normal;
font-weight: normal;
font-size: 12px;
line-height: 16px;
```

# Inactive State Display on Home Page 

When a site is inactive, it will show as "coming soon" on foodouken.com in a separate list, under the currently active stores 
![image](https://user-images.githubusercontent.com/14948326/87398668-69682300-c5e0-11ea-96c6-7702e7983c33.png)

**Content** 
Card Overlay Text: Coming Soon

**Text Style** 
Card Overlay Text: 
```
/* Mobile H1 */

font-family: Open Sans;
font-style: normal;
font-weight: bold;
font-size: 32px;
line-height: 44px;
```
**Color** 
Divider: Divider (#FFFFFF, 12%) 
Overlay: (#000000, 54%)
Overlay Text: On Surface, Medium (#FFFFFF, 54%)

**Comment by paulchrisluke** [comment]
@ctyar do we have an active not active endpoint?

**Comment by ctyar** [comment]
@paulchrisluke not for tenants, we implemented something similar for products though

**Comment by paulchrisluke** [comment]
Ok added backend issue in priority milestone https://github.com/whynotearth/meredith-core/issues/261

**Comment by paulchrisluke** [comment]
@giteshk11 one thing I missed in my review, is that users should not be able to click on the "coming soon" stores since they can't order. Can we disable interaction there?

**Comment by giteshk11** [comment]
@paulchrisluke Sure, i'll see

**Comment by bamboochow** [comment]
# Active State 
"Active" sites still show "draft mode" in activation status, should say "Current Status - Active" 
![image](https://user-images.githubusercontent.com/14948326/87744259-335fb480-c815-11ea-8a3f-b6029640d6c0.png)

# Customer View "Coming soon" 

Currently the site shows "coming soon" cards displayed in their previous position 
Disabled restaurants have their card displayed as "coming soon" and should be moved to a different section separated by a divider 
![image](https://user-images.githubusercontent.com/14948326/87744363-89345c80-c815-11ea-8c0f-82b4da9bebe0.png)
![image](https://user-images.githubusercontent.com/14948326/87744565-f942e280-c815-11ea-8ddf-84eab3fc01ec.png)
